#file: noinspection SpringBootApplicationYaml
## mssql
#spring:
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost;databaseName=hyunblog;encrypt=true;trustServerCertificate=true
#    username: ph
#    password: 1024612a!
#  jpa:
#    hibernate:
#     ddl-auto: create #create update none
#     naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
jwt:
  secret: VlwEyVBsYtaiwnQDKw9211V7zq57TejMnVUyzblYcfPQye08f7PHYUNM89XkHa

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hyunBlog?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1024612a!

server:
  port: 8080

# Mybatis 설정
mybatis:
  # default Package location - resultType의 Alias를 지정합니다.
  type-aliases-package: hyun.query.mapper
  # mapper location - 바라 볼 xml 파일을 지정합니다.
  mapper-locations: classpath:hyun/query/mapper/*.xml
  # column name to camel case - 반환 받는 컬럼명을 CamelCase로 받는 설정을 합니다.
  configuration:
    map-underscore-to-camel-case: true



 