#file: noinspection SpringBootApplicationYaml
## mssql
#spring:
#  datasource:
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost;databaseName=hyunblog;encrypt=true;trustServerCertificate=true
#    username: ph
#    password: 1024612a!
#  jpa:
#    hibernate:
#     ddl-auto: create #create update none
#     naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
jwt:
  secret: VlwEyVBsYtaiwnQDKw9211V7zq57TejMnVUyzblYcfPQye08f7PHYUNM89XkHa

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hyun?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

server:
  port: 8080

# Mybatis 설정...
mybatis:

datasource:
  # Log4jdbcProxyDataSource를 사용하여 데이터 소스를 설정.
  # dataSourceSpied는 Log4jdbcProxyDataSource의 생성자에 전달.
  dataSource:
    type: "net.sf.log4jdbc.Log4jdbcProxyDataSource"
    constructor-args:
      - ref: "dataSourceSpied"
    properties:
      logFormatter:
        # Log4JdbcCustomFormatter를 사용하여 로그 형식을 지정.
        type: "net.sf.log4jdbc.tools.Log4JdbcCustomFormatter"
        properties:
          loggingType: "MULTI_LINE"  # 로그 유형을 다중 라인으로 지정.
          sqlPrefix: "SQL:::"  # SQL 문 앞에 붙일 접두사를 지정.

  beans:
    sqlSessionFactory:
      class: com.hyun.config.refreshMybatis
      properties:
        mapperLocations: classpath:hyun/sqlmap/**/*.xml
        configLocation: classpath:hyun/mybatis-config.xml
        dataSource: '@dataSource'


 